import type { Metadata } from "next";
import { Inter, Catamaran, Poppins } from "next/font/google";
import "./globals.css";
import Header from "./home/components/header";
import NavBar from "./home/components/navBar";
import Footer from "./home/components/footer";
import { fetcHomehData } from "./lib";
// import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
// import theme from "@/theme";
// import { ThemeProvider } from "@emotion/react";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
const inter = Inter({ subsets: ["latin"] });
const catamaran = Catamaran({
  subsets: ["latin"],
  display: "auto",
  variable: "--font-catamaran",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});
const poppins = Poppins({
  subsets: ["latin"],
  display: "auto",
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Installer folan",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const response = await fetcHomehData();

  return (
    <html lang="en">
      <body
        className={`${inter.className} ${catamaran.variable} ${poppins.variable}`}
      >
        {/* <AppRouterCacheProvider options={{ key: "css" }}> */}
        {/* <ThemeProvider theme={theme}>  */}
        <Header data={response} />
        <NavBar data={response} />
        <ToastContainer />

        {children}
        <Footer data={response} />

        {/* </ThemeProvider> */}
        {/* </AppRouterCacheProvider> */}
      </body>
    </html>
  );
}
